In [28]:
from google.colab import files

uploaded = files.upload()

Saving mail_data.csv to mail_data (1).csv

In [29]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [30]:
df = pd.read_csv("mail_data.csv", encoding="latin-1")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [31]:
df = df[['Category','Message']]
df.columns = ['label','message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [32]:
print(df.shape)

df['label'].value_counts()

(5572, 2)

label
ham     4825
spam     747
Name: count, dtype: int64

In [33]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [34]:
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

In [35]:
df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [36]:
X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [37]:
vectorizer = TfidfVectorizer()
X_train_features = vectorizer.fit_transform(X_train)

X_test_features = vectorizer.transform(X_test)

In [38]:
print(len(vectorizer.vocabulary_))

7733

In [39]:
model = MultinomialNB()

model.fit(
    X_train_features,
    y_train
)

MultinomialNB()

In [40]:
predictions = model.predict(
    X_test_features
)

In [41]:
accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy:", accuracy)

Accuracy: 0.9632286995515695

In [42]:
print(classification_report(
    y_test,
    predictions
))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       1.00      0.72      0.84       149

    accuracy                           0.96      1115
   macro avg       0.98      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115

In [43]:
email = [
    "Hooray! You have won an iPhone through your hardwork.click here to claim your prize, Hi, how are you?"
]

email_vector = vectorizer.transform(email)

prediction = model.predict(email_vector)

if prediction[0] == 1:
    print("Spam")
else:
    print("Not Spam")

Not Spam

In [46]:
import pickle

pickle.dump(model, open("spam_model.pkl","wb"))
pickle.dump(vectorizer, open("vectorizer.pkl","wb"))

In [48]:
from google.colab import files

files.download("spam_model.pkl")
files.download("vectorizer.pkl")